// -----------------------------------------------------------------------------
// Minimal SmartThings Cloud API client (uses the Node.js built-in fetch).
//
// The SmartThings Cloud API (https://api.smartthings.com/v1) is authenticated
// with a bearer token. This integration uses a Personal Access Token (PAT)
// generated by the user at https://account.smartthings.com/tokens — a static
// token, so there is no login / refresh handshake (unlike an OAuth2 flow).
//
//   - GET  /devices                    -> list of devices (paginated)
//   - GET  /devices/{id}/status        -> full status (components -> capabilities)
//   - POST /devices/{id}/commands      -> send one or more commands
//
// A 401 means the token is missing, invalid or expired (SmartThings PATs
// created since late 2024 expire after 24h): the error is surfaced so the
// integration can report it in the Gladys UI.
// -----------------------------------------------------------------------------

import { createLogger } from '@gladysassistant/integration-sdk';

import { SMARTTHINGS_ENDPOINT } from '../constants.js';

const logger = createLogger({ name: 'smartthings' });

const REQUEST_TIMEOUT_MS = 15000;

export class SmartThingsClient {
  constructor(baseUrl = SMARTTHINGS_ENDPOINT) {
    this.baseUrl = baseUrl.replace(/\/+$/, '');
    this.token = null;
  }

  isConfigured() {
    return this.token !== null;
  }

  /**
   * Store the Personal Access Token used for every request.
   * @param {string} token SmartThings Personal Access Token
   */
  setToken(token) {
    this.token = token || null;
  }

  clearToken() {
    this.token = null;
  }

  /**
   * List every device visible to the token, following the API pagination.
   * @returns {Promise<Array>} the raw SmartThings device objects
   */
  async listDevices() {
    const devices = [];
    let path = 'devices';
    // Follow `_links.next` until the API stops returning one (guarded against
    // a runaway loop).
    for (let page = 0; path && page < 50; page += 1) {
      const response = await this.#authenticatedRequest(path);
      devices.push(...(response.items || []));
      path = this.#nextPagePath(response);
    }
    logger.debug(`${devices.length} devices loaded`);
    return devices;
  }

  /**
   * Fetch the live status of one device (all components / capabilities).
   * @param {string} deviceId SmartThings device id
   * @returns {Promise<object>} the device status ({ components: { main: {...} } })
   */
  async getDeviceStatus(deviceId) {
    return this.#authenticatedRequest(`devices/${encodeURIComponent(deviceId)}/status`);
  }

  /**
   * Send commands to a device.
   * @param {string} deviceId SmartThings device id
   * @param {Array<object>} commands array of { component, capability, command, arguments }
   */
  async sendCommands(deviceId, commands) {
    return this.#authenticatedRequest(`devices/${encodeURIComponent(deviceId)}/commands`, {
      method: 'POST',
      body: JSON.stringify({ commands }),
      contentType: 'application/json',
    });
  }

  /**
   * Turn an absolute or relative `_links.next.href` into a path relative to the
   * API base, so it can be fed back to #fetchJson.
   */
  #nextPagePath(response) {
    const next = response && response._links && response._links.next && response._links.next.href;
    if (!next) {
      return null;
    }
    // The API may return an absolute URL; keep only the part after the base.
    if (next.startsWith('http')) {
      const url = new URL(next);
      return `${url.pathname.replace(/^\/v1\//, '')}${url.search}`;
    }
    return next.replace(/^\/?(v1\/)?/, '');
  }

  async #authenticatedRequest(path, options = {}) {
    if (!this.isConfigured()) {
      throw new Error('SmartThings is not configured (missing Personal Access Token)');
    }
    return this.#fetchJson(path, {
      ...options,
      headers: { Authorization: `Bearer ${this.token}` },
    });
  }

  async #fetchJson(path, { method = 'GET', headers = {}, body, contentType }) {
    const response = await fetch(`${this.baseUrl}/${path}`, {
      method,
      headers: {
        Accept: 'application/json',
        ...(contentType ? { 'Content-Type': contentType } : {}),
        ...headers,
      },
      body,
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    });
    if (!response.ok) {
      const error = new Error(
        `SmartThings request failed: ${method} ${path} -> HTTP ${response.status}`,
      );
      error.status = response.status;
      throw error;
    }
    // Command endpoints may answer with an empty body.
    const text = await response.text();
    return text ? JSON.parse(text) : {};
  }
}
